### ISSUE TITLE
Not check for null string bug

### ISSUE THREAD

**Issue by SepiaGroup** [noraesae/react-render-html#15]
if you pass a null string you get an error. can you please update the following to check for null/undefined html. 

this happens to me since i am pulling values out of redux and they are no always loaded at render time. 
 
```
var renderHTML = function (html) {
  var htmlAST = htmlParser.parseFragment(html);

  if (htmlAST.childNodes.length === 0) {
    return null;
  }

  var result = htmlAST.childNodes.map(renderNode);

  return result.length === 1 ? result[0] : result;
};
```

**Comment by noraesae** [comment]
I'm not sure if the function should take care of null by itself. I think the data should be sanitized before being provided into the function.

I am afraid I may not accept the suggestion. Sorry afain, but thank you for the suggestion.

**Comment by SepiaGroup** [comment]
wouldn't it be better to return a null then throw an error? 

i don't know of any component that i use with react that throws and error because of passing in a null/undefined value, they just return null. throwing an error in this case is not the norm and is unexpected. 

in fact, in the next line of code you check to see if there are child nodes created from the input string and if not you return a null instead of throwing an error.  why do you not throw an error in this case too? so now have to remember to test my input to this one function and pass in a zero length string if it is null just to receive a null back and not have an error thrown. this is really not the norm.

**Comment by noraesae** [comment]
Because an empty string is a valid HTML string which normal HTML parsers can parse. In the case, the result should be just an empty component, which is `null` in React. `null` or `undefined` is not a valid HTML string, and should be handled as an exception. I'm not sure of other components, but silently ignoring exceptions and returning null is not a good practice in my thought.

Sorry again for not accepting the suggestion, although I appreciate your contribution.
